name: rb_invoice
description: Aplikasi Invoice RB Invoice
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  sqflite: ^2.3.0
  path: ^1.8.3

  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
